[package]
name = "global"
version = "0.1.0"
edition = "2021"

[dependencies]
ethnum = "1.2.2"
hmac-sha256 = "1.1.4"
serde = { version = "1.0.143", features = ["serde_derive"] }
prime_field = { path = "../prime_field" }
